import type { RoleState } from "@/lib/roles";
import type { TournamentRow } from "@/lib/tournaments";

export type AutomationMode = "manual" | "automatic";
export type OneCheckedInTimeoutPolicy = "forfeit_checked_in" | "staff_review";
export type NeitherCheckedInTimeoutPolicy = "no_contest" | "random_advancement" | "staff_review";
export type BothCheckedInNoResultPolicy = "no_contest" | "staff_review";
export type OneReportNoResponsePolicy = "staff_review";

export type TournamentAutomationPolicy = {
  autoAdvanceGroupRoundWaves: boolean;
  autoApplyMatchTimeoutOutcomes: boolean;
  autoCloseCheckInAtDeadline: boolean;
  autoCloseRegistrationAtDeadline: boolean;
  autoCloseReplacementWindowAtDeadline: boolean;
  autoGenerateDrawAfterReplacement: boolean;
  autoGeneratePlayoffWhenGroupsResolved: boolean;
  autoOpenCheckInAtStartTime: boolean;
  autoOpenReadyMatches: boolean;
  autoOpenReplacementWindowIfSpotsAvailable: boolean;
  automationMode: AutomationMode;
  automationPausedAt: string | null;
  bothCheckedInNoResultPolicy: BothCheckedInNoResultPolicy;
  neitherCheckedInBracketPolicy: NeitherCheckedInTimeoutPolicy;
  neitherCheckedInGroupPolicy: NeitherCheckedInTimeoutPolicy;
  oneCheckedInTimeoutPolicy: OneCheckedInTimeoutPolicy;
  oneReportNoResponsePolicy: OneReportNoResponsePolicy;
};

export type TournamentAutomationEventRow = {
  actor_id: string | null;
  actor_type: "system" | "organizer" | "admin";
  created_at: string;
  details: Record<string, unknown>;
  event_type: string;
  id: string;
  source: "live_control" | "page_poll" | "manual_button";
  tournament_id: string;
};

export type AutomationActionKind =
  | "close_registration"
  | "open_check_in"
  | "apply_check_in_expiry"
  | "apply_replacement_expiry"
  | "generate_group_draw"
  | "generate_bracket"
  | "open_ready_matches"
  | "apply_group_round_expiry"
  | "apply_bracket_round_expiry"
  | "generate_group_playoff";

export const automationModeLabels: Record<AutomationMode, string> = {
  automatic: "Automatic",
  manual: "Manual",
};

export const oneCheckedInTimeoutPolicyLabels: Record<OneCheckedInTimeoutPolicy, string> = {
  forfeit_checked_in: "Checked-in player wins by FF",
  staff_review: "Staff review",
};

export const neitherCheckedInTimeoutPolicyLabels: Record<NeitherCheckedInTimeoutPolicy, string> = {
  no_contest: "No contest",
  random_advancement: "Random advancement",
  staff_review: "Staff review",
};

export const bothCheckedInNoResultPolicyLabels: Record<BothCheckedInNoResultPolicy, string> = {
  no_contest: "No contest",
  staff_review: "Staff review",
};

export const oneReportNoResponsePolicyLabels: Record<OneReportNoResponsePolicy, string> = {
  staff_review: "Staff review",
};

export function getDefaultAutomationPolicy(): TournamentAutomationPolicy {
  return {
    autoAdvanceGroupRoundWaves: true,
    autoApplyMatchTimeoutOutcomes: false,
    autoCloseCheckInAtDeadline: false,
    autoCloseRegistrationAtDeadline: false,
    autoCloseReplacementWindowAtDeadline: false,
    autoGenerateDrawAfterReplacement: false,
    autoGeneratePlayoffWhenGroupsResolved: false,
    autoOpenCheckInAtStartTime: false,
    autoOpenReadyMatches: true,
    autoOpenReplacementWindowIfSpotsAvailable: false,
    automationMode: "manual",
    automationPausedAt: null,
    bothCheckedInNoResultPolicy: "staff_review",
    neitherCheckedInBracketPolicy: "staff_review",
    neitherCheckedInGroupPolicy: "no_contest",
    oneCheckedInTimeoutPolicy: "forfeit_checked_in",
    oneReportNoResponsePolicy: "staff_review",
  };
}

function normalizeMode(value: unknown, fallback: AutomationMode): AutomationMode {
  if (value === "automatic" || value === "hands_off") {
    return "automatic";
  }

  return value === "manual" || value === "assisted" ? "manual" : fallback;
}

function normalizeOneCheckedInPolicy(
  value: unknown,
  fallback: OneCheckedInTimeoutPolicy,
): OneCheckedInTimeoutPolicy {
  return value === "forfeit_checked_in" || value === "staff_review" ? value : fallback;
}

function normalizeNeitherCheckedInPolicy(
  value: unknown,
  fallback: NeitherCheckedInTimeoutPolicy,
): NeitherCheckedInTimeoutPolicy {
  return value === "no_contest" || value === "random_advancement" || value === "staff_review"
    ? value
    : fallback;
}

function normalizeBothCheckedInPolicy(
  value: unknown,
  fallback: BothCheckedInNoResultPolicy,
): BothCheckedInNoResultPolicy {
  return value === "no_contest" || value === "staff_review" ? value : fallback;
}

export function normalizeAutomationPolicy(
  tournament: Partial<TournamentRow> | TournamentAutomationPolicy,
): TournamentAutomationPolicy {
  const defaults = getDefaultAutomationPolicy();

  if ("automationMode" in tournament) {
    return {
      ...defaults,
      ...tournament,
      automationMode: normalizeMode(tournament.automationMode, defaults.automationMode),
      bothCheckedInNoResultPolicy: normalizeBothCheckedInPolicy(
        tournament.bothCheckedInNoResultPolicy,
        defaults.bothCheckedInNoResultPolicy,
      ),
      neitherCheckedInBracketPolicy: normalizeNeitherCheckedInPolicy(
        tournament.neitherCheckedInBracketPolicy,
        defaults.neitherCheckedInBracketPolicy,
      ),
      neitherCheckedInGroupPolicy: normalizeNeitherCheckedInPolicy(
        tournament.neitherCheckedInGroupPolicy,
        defaults.neitherCheckedInGroupPolicy,
      ),
      oneCheckedInTimeoutPolicy: normalizeOneCheckedInPolicy(
        tournament.oneCheckedInTimeoutPolicy,
        defaults.oneCheckedInTimeoutPolicy,
      ),
      oneReportNoResponsePolicy: "staff_review",
    };
  }

  return {
    autoAdvanceGroupRoundWaves:
      tournament.auto_advance_group_round_waves ?? defaults.autoAdvanceGroupRoundWaves,
    autoApplyMatchTimeoutOutcomes:
      tournament.auto_apply_match_timeout_outcomes ??
      tournament.auto_apply_timer_outcomes ??
      defaults.autoApplyMatchTimeoutOutcomes,
    autoCloseCheckInAtDeadline:
      tournament.auto_close_check_in_at_deadline ?? defaults.autoCloseCheckInAtDeadline,
    autoCloseRegistrationAtDeadline:
      tournament.auto_close_registration_at_deadline ?? defaults.autoCloseRegistrationAtDeadline,
    autoCloseReplacementWindowAtDeadline:
      tournament.auto_close_replacement_window_at_deadline ??
      defaults.autoCloseReplacementWindowAtDeadline,
    autoGenerateDrawAfterReplacement:
      tournament.auto_generate_draw_after_replacement ?? defaults.autoGenerateDrawAfterReplacement,
    autoGeneratePlayoffWhenGroupsResolved:
      tournament.auto_generate_playoff_when_groups_resolved ??
      defaults.autoGeneratePlayoffWhenGroupsResolved,
    autoOpenCheckInAtStartTime:
      tournament.auto_open_check_in_at_start_time ?? defaults.autoOpenCheckInAtStartTime,
    autoOpenReadyMatches: tournament.auto_open_ready_matches ?? defaults.autoOpenReadyMatches,
    autoOpenReplacementWindowIfSpotsAvailable:
      tournament.auto_open_replacement_window_if_spots_available ??
      defaults.autoOpenReplacementWindowIfSpotsAvailable,
    automationMode: normalizeMode(tournament.automation_mode, defaults.automationMode),
    automationPausedAt: tournament.automation_paused_at ?? null,
    bothCheckedInNoResultPolicy: normalizeBothCheckedInPolicy(
      tournament.both_checked_in_no_result_policy,
      defaults.bothCheckedInNoResultPolicy,
    ),
    neitherCheckedInBracketPolicy: normalizeNeitherCheckedInPolicy(
      tournament.neither_checked_in_bracket_policy,
      defaults.neitherCheckedInBracketPolicy,
    ),
    neitherCheckedInGroupPolicy: normalizeNeitherCheckedInPolicy(
      tournament.neither_checked_in_group_policy,
      defaults.neitherCheckedInGroupPolicy,
    ),
    oneCheckedInTimeoutPolicy: normalizeOneCheckedInPolicy(
      tournament.one_checked_in_timeout_policy,
      defaults.oneCheckedInTimeoutPolicy,
    ),
    oneReportNoResponsePolicy: "staff_review",
  };
}

export function buildAutomationPolicyPayload(policy: TournamentAutomationPolicy) {
  return {
    auto_advance_group_round_waves: policy.autoAdvanceGroupRoundWaves,
    auto_apply_match_timeout_outcomes: policy.autoApplyMatchTimeoutOutcomes,
    auto_apply_timer_outcomes: policy.autoApplyMatchTimeoutOutcomes,
    auto_close_check_in_at_deadline: policy.autoCloseCheckInAtDeadline,
    auto_close_registration_at_deadline: policy.autoCloseRegistrationAtDeadline,
    auto_close_replacement_window_at_deadline: policy.autoCloseReplacementWindowAtDeadline,
    auto_generate_draw_after_replacement: policy.autoGenerateDrawAfterReplacement,
    auto_generate_playoff_when_groups_resolved: policy.autoGeneratePlayoffWhenGroupsResolved,
    auto_open_check_in_at_start_time: policy.autoOpenCheckInAtStartTime,
    auto_open_ready_matches: policy.autoOpenReadyMatches,
    auto_open_replacement_window_if_spots_available:
      policy.autoOpenReplacementWindowIfSpotsAvailable,
    automation_mode: policy.automationMode,
    automation_paused_at: policy.automationPausedAt,
    both_checked_in_no_result_policy: policy.bothCheckedInNoResultPolicy,
    neither_checked_in_bracket_policy: policy.neitherCheckedInBracketPolicy,
    neither_checked_in_group_policy: policy.neitherCheckedInGroupPolicy,
    one_checked_in_timeout_policy: policy.oneCheckedInTimeoutPolicy,
    one_report_no_response_policy: policy.oneReportNoResponsePolicy,
  };
}

export function canEditAutomationPolicy(
  tournament: Pick<TournamentRow, "created_by">,
  roles: RoleState,
  userId: string | null,
  isManagedByUser: boolean,
) {
  return Boolean(userId && (roles.isAdmin || tournament.created_by === userId || isManagedByUser));
}

export function getAutomationModeLabel(policyOrMode: TournamentAutomationPolicy | AutomationMode) {
  const mode = typeof policyOrMode === "string" ? policyOrMode : policyOrMode.automationMode;

  return automationModeLabels[mode];
}

export function isAutomationPaused(policy: TournamentAutomationPolicy) {
  return Boolean(policy.automationPausedAt);
}

export function shouldRunAutomaticAutomation(policy: TournamentAutomationPolicy) {
  return policy.automationMode === "automatic" && !isAutomationPaused(policy);
}

export function getAutomationPolicyWarnings(policy: TournamentAutomationPolicy) {
  const warnings: string[] = [];

  if (policy.automationMode === "automatic") {
    warnings.push("Automatic mode can apply enabled safe timer transitions from page activity.");
  }

  if (
    policy.neitherCheckedInBracketPolicy === "random_advancement" ||
    policy.neitherCheckedInGroupPolicy === "random_advancement"
  ) {
    warnings.push("Random advancement is enabled. It advances the tournament but is excluded from public player records.");
  }

  if (policy.automationPausedAt) {
    warnings.push("Automation is paused. Automatic actions will not run until resumed.");
  }

  return warnings;
}

export function getEnabledAutomationToggleLabels(policy: TournamentAutomationPolicy) {
  const labels: string[] = [];

  if (policy.autoCloseRegistrationAtDeadline) labels.push("Close registration at deadline");
  if (policy.autoOpenCheckInAtStartTime) labels.push("Open check-in at start time");
  if (policy.autoCloseCheckInAtDeadline) labels.push("Close check-in at deadline");
  if (policy.autoOpenReplacementWindowIfSpotsAvailable) labels.push("Open replacement window");
  if (policy.autoCloseReplacementWindowAtDeadline) labels.push("Close replacement window");
  if (policy.autoGenerateDrawAfterReplacement) labels.push("Generate draw/bracket after replacement");
  if (policy.autoOpenReadyMatches) labels.push("Open ready matches");
  if (policy.autoApplyMatchTimeoutOutcomes) labels.push("Apply match timeout outcomes");
  if (policy.autoAdvanceGroupRoundWaves) labels.push("Advance group round waves");
  if (policy.autoGeneratePlayoffWhenGroupsResolved) labels.push("Generate playoff when groups resolve");

  return labels;
}

export function isAutomationActionEnabled(
  kind: AutomationActionKind,
  policy: TournamentAutomationPolicy,
) {
  if (kind === "close_registration") return policy.autoCloseRegistrationAtDeadline;
  if (kind === "open_check_in") return policy.autoOpenCheckInAtStartTime;
  if (kind === "apply_check_in_expiry") return policy.autoCloseCheckInAtDeadline;
  if (kind === "apply_replacement_expiry") return policy.autoCloseReplacementWindowAtDeadline;
  if (kind === "generate_group_draw" || kind === "generate_bracket") {
    return policy.autoGenerateDrawAfterReplacement;
  }
  if (kind === "open_ready_matches") {
    return policy.autoOpenReadyMatches || policy.autoAdvanceGroupRoundWaves;
  }
  if (kind === "apply_group_round_expiry" || kind === "apply_bracket_round_expiry") {
    return policy.autoApplyMatchTimeoutOutcomes;
  }
  if (kind === "generate_group_playoff") return policy.autoGeneratePlayoffWhenGroupsResolved;

  return false;
}

export function formatAutomationEvent(event: TournamentAutomationEventRow) {
  const label = event.event_type
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");

  return `${label} via ${event.source.replace("_", " ")}`;
}

export function generateAutomationRulesText(
  tournament: Pick<
    TournamentRow,
    | "auto_advance_group_round_waves"
    | "auto_apply_match_timeout_outcomes"
    | "auto_apply_timer_outcomes"
    | "auto_close_check_in_at_deadline"
    | "auto_close_registration_at_deadline"
    | "auto_close_replacement_window_at_deadline"
    | "auto_generate_draw_after_replacement"
    | "auto_generate_playoff_when_groups_resolved"
    | "auto_open_check_in_at_start_time"
    | "auto_open_ready_matches"
    | "auto_open_replacement_window_if_spots_available"
    | "automation_mode"
    | "automation_paused_at"
    | "both_checked_in_no_result_policy"
    | "neither_checked_in_bracket_policy"
    | "neither_checked_in_group_policy"
    | "one_checked_in_timeout_policy"
    | "one_report_no_response_policy"
  >,
) {
  const policy = normalizeAutomationPolicy(tournament);
  const neitherPolicyText =
    policy.neitherCheckedInGroupPolicy === policy.neitherCheckedInBracketPolicy
      ? neitherCheckedInTimeoutPolicyLabels[policy.neitherCheckedInGroupPolicy]
      : `Groups: ${neitherCheckedInTimeoutPolicyLabels[policy.neitherCheckedInGroupPolicy]}; bracket: ${neitherCheckedInTimeoutPolicyLabels[policy.neitherCheckedInBracketPolicy]}`;

  return [
    `Automation mode: ${automationModeLabels[policy.automationMode]}. ${
      policy.automationMode === "automatic"
        ? "When a timer expires, enabled safe transitions may be applied automatically from page activity or Live Control polling."
        : "The system shows recommendations, and tournament staff applies actions manually."
    }`,
    policy.autoCloseCheckInAtDeadline
      ? "Check-in may be closed automatically at the configured deadline."
      : "Check-in close requires tournament staff action.",
    policy.autoOpenReplacementWindowIfSpotsAvailable
      ? "If spots are available after check-in closes, the replacement window may open automatically."
      : "Replacement window opening requires tournament staff action.",
    policy.autoCloseReplacementWindowAtDeadline
      ? "The replacement window may close automatically at its deadline."
      : "Replacement close requires tournament staff action.",
    policy.autoGenerateDrawAfterReplacement
      ? "After replacement closes, the draw or bracket may be generated automatically when safe."
      : "Draw and bracket generation require tournament staff action.",
    policy.autoOpenReadyMatches
      ? "Ready matches may open automatically when both players are known."
      : "Ready matches open when tournament staff advances operations.",
    policy.autoApplyMatchTimeoutOutcomes
      ? "Expired group or bracket timers may apply the configured timeout outcomes."
      : "Expired match timers require tournament staff confirmation.",
    `If exactly one player checks into a match room and the opponent does not, policy: ${oneCheckedInTimeoutPolicyLabels[policy.oneCheckedInTimeoutPolicy]}.`,
    `If neither player checks into a match room before timer expiry, policy: ${neitherPolicyText}.`,
    `If both players check in but no result is submitted, policy: ${bothCheckedInNoResultPolicyLabels[policy.bothCheckedInNoResultPolicy]}.`,
    `If one player submits a result and the other does not respond, policy: ${oneReportNoResponsePolicyLabels[policy.oneReportNoResponsePolicy]}.`,
    "Forfeits may affect group standings but do not count toward public player records. BYEs, no-contests, and random timeout advancement do not count toward public player records.",
    "Tournament staff can pause, extend, force close, switch to Manual, or override in emergencies.",
  ].join("\n\n");
}
